// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://benvqbuizxxsvfdblsxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlbnZxYnVpenh4c3ZmZGJsc3hmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNjgzNzgsImV4cCI6MjA1ODk0NDM3OH0.aOJd77gIdRr01csHCaULlDStw8U3F3Hfx8TNhFRZp2o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);